# simple_config_file:
#   plugin: virtualbox
#   groups: windows
windows:
  hosts:
    '192.168.99.100':
  vars:
    ansible_user: Administrator
    ansible_password: Pa55w0rd
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
